### PR TITLE
Update ctf_setup.sh | netcat not installed on linux instance

### PR DESCRIPTION
**Pull request by Ayolowo**
netcat not installed on Linux instance which prevents the [nc -l -p] command from executing

### CODE REVIEW

**Comment by madebygps** [comment]
@rishabkumar7 this seems to address the issue discussed in the discord

**Comment by rishabkumar7** [comment]
https://github.com/learntocloud/ltc-linux-challenge/pull/7

**Comment by madebygps** [comment]
we've updated the guide to instruct instead of applying the exact change, thank you

**Comment by Ayolowo** [comment]
@rishabkumar7 yes I agree, I was thinking the same thing, and shared another approach with Gwyneth. It gives everyone the opportunity to also learn.
@madebygps great work Gwyneth

**Comment by rishabkumar7** [comment]
Cool, yeah I included it in the hint section, here is the PR - https://github.com/learntocloud/ltc-linux-challenge/pull/7

**Comment by Ayolowo** [comment]
> Cool, yeah I included it in the hint section, here is the PR - #7

This is wonderful, great work! @rishabkumar7

**Comment by Ayolowo** [comment]
@rishabkumar7 check this out

error running nc

**Comment by rishabkumar7** [comment]
@Ayolowo wait, what is that output of?

**Comment by Ayolowo** [comment]
@rishabkumar7 the output was gotten from executing the port_8080_service.sh file within the Linux instance, I did that because I could not find any process running on port 8080. The output shows there's an issue with netcat - nc, not netstat.

**Comment by rishabkumar7** [comment]
@Ayolowo oh good catch, testing something, will merge this once tests complete.

**Review by rishabkumar7 — APPROVED** [review]
lgtm

**Comment by Ayolowo** [comment]
@rishabkumar7 cool! great work.

**Comment by rishabkumar7** [comment]
thanks @Ayolowo for covering other clouds as well. LGTM!

**Review by rishabkumar7 — APPROVED** [review]

**Comment by Ayolowo** [comment]
you are most welcome @rishabkumar7

**Pull request merged**
